<a href="https://colab.research.google.com/github/mohamedalaaaz/testpytroch/blob/main/learn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world the graetes")

hello world the graetes


In [4]:
import torch

In [5]:
print(torch.__version__)

2.6.0+cu124


In [6]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
import torch
x= torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [21]:
x_reshaped=x.reshape(1 ,9)
x_reshaped ,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [20]:
x_reshaped=x.reshape(9,1)
x_reshaped ,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [24]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [33]:
z[:,0] = 5
z,x ,z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([1, 9]))

In [41]:
x_stack=torch.stack([x,x,x,x,x] ,dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [51]:
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape,

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
x[0][0]


tensor([1, 2, 3])

In [62]:
x[0][2][2]

tensor(9)

In [63]:
x[:,1]

tensor([[4, 5, 6]])

In [64]:
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
x[:,1,1]

tensor([5])

In [67]:
x[0,0,:]

tensor([1, 2, 3])

In [68]:
x[0,1,:]

tensor([4, 5, 6])

In [69]:
x[0,2,:]

tensor([7, 8, 9])

In [73]:
x[0,2,2]

tensor(9)

In [74]:
x[:,:,2]

tensor([[3, 6, 9]])

In [76]:
import torch
import numpy as np

array = np.arange (1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

TypeError: 'tuple' object is not callable