<a href="https://colab.research.google.com/github/mohamedalaaaz/testpytroch/blob/main/testcomapny.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float64)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
array.dtype

dtype('float64')

In [10]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [11]:
tensor=tensor+2
tensor,numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
torch.rand(280,2855)

tensor([[8.1939e-01, 3.6416e-01, 4.7114e-02,  ..., 8.3350e-01, 9.6599e-02,
         2.3510e-01],
        [5.6239e-02, 4.8720e-01, 3.5220e-01,  ..., 5.0327e-01, 3.6526e-01,
         8.6804e-01],
        [3.2172e-01, 1.5105e-01, 1.1925e-01,  ..., 6.1857e-01, 1.3728e-01,
         4.0474e-01],
        ...,
        [9.8552e-01, 4.0568e-01, 9.8673e-01,  ..., 8.4936e-01, 7.1429e-01,
         4.8049e-01],
        [4.8403e-01, 6.8079e-01, 6.0515e-01,  ..., 3.0649e-01, 4.3356e-04,
         5.6871e-02],
        [1.4621e-01, 1.2673e-01, 3.6693e-01,  ..., 3.5623e-01, 1.8607e-01,
         7.6970e-01]])

In [15]:
torch.rand(9,9)

tensor([[0.8084, 0.5151, 0.4784, 0.3633, 0.3095, 0.9801, 0.3502, 0.0132, 0.9658],
        [0.6534, 0.8214, 0.9410, 0.6488, 0.1995, 0.1772, 0.9166, 0.4789, 0.6520],
        [0.9453, 0.1930, 0.3105, 0.6495, 0.3167, 0.4476, 0.4149, 0.0951, 0.4740],
        [0.6977, 0.1772, 0.0063, 0.8514, 0.6106, 0.2125, 0.4054, 0.3449, 0.0575],
        [0.8605, 0.1892, 0.3943, 0.5352, 0.2771, 0.6847, 0.6625, 0.6165, 0.8630],
        [0.5711, 0.1938, 0.2328, 0.7759, 0.4396, 0.2220, 0.5180, 0.2324, 0.8347],
        [0.7849, 0.1832, 0.6812, 0.6340, 0.5874, 0.0855, 0.9703, 0.3572, 0.1195],
        [0.1950, 0.7859, 0.1750, 0.9278, 0.3780, 0.7812, 0.5467, 0.2890, 0.9369],
        [0.2730, 0.6157, 0.5901, 0.9189, 0.8129, 0.3654, 0.4829, 0.4441, 0.2742]])

In [17]:
import torch
random_tensor_A =torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A )
print(random_tensor_B )
print(random_tensor_A  ==random_tensor_B)


tensor([[0.8520, 0.4046, 0.8719, 0.0998],
        [0.9363, 0.8831, 0.3656, 0.6329],
        [0.5200, 0.6085, 0.9564, 0.9629]])
tensor([[0.9647, 0.2139, 0.5611, 0.1431],
        [0.3923, 0.3266, 0.1376, 0.6557],
        [0.7228, 0.0694, 0.5563, 0.2540]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [21]:
import torch
seed_rendom=55
torch.manual_seed(seed_rendom)
random_tensor_C=torch.rand(3,4)
random_tensor_d=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_d )
print(random_tensor_C ==random_tensor_d)

tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[0.8334, 0.7835, 0.5216, 0.8003],
        [0.7370, 0.3124, 0.3930, 0.3130],
        [0.1657, 0.8543, 0.5834, 0.5361]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [22]:
import torch
seed_rendom=55
torch.manual_seed(seed_rendom)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(seed_rendom)
random_tensor_d=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_d )
print(random_tensor_C ==random_tensor_d)

tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [30]:
import random
random.seed(0)
import torch
torch.use_deterministic_algorithms(True)
#torch.bmm(torch.randn(2, 2, 2).to_sparse().cuda(), torch.randn(2, 2, 2).cuda())


In [35]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [36]:
import torch
torch.cuda.is_available()

False

In [37]:
torch.cuda.device_count()

0